kapke_my_place:
    resource: "@KapkeMyPlaceBundle/Resources/config/routing.yml"
    prefix:   /
module_client_conversions:
    resource: "@KapkeClientConversionsModuleBundle/Resources/config/routing.yml"
    prefix:   /client_conversions/
module_client_data:
    resource: "@KapkeClientDataModuleBundle/Resources/config/routing.yml"
    prefix:   /client_data/
module_notes:
    resource: "@KapkeNotesModuleBundle/Resources/config/routing.yml"
    prefix:   /notes/
