parameters:
#    kapke_my_place.example.class: Kapke\Bundle\MyPlaceBundle\Example

services:
    kapke_my_place.modules_manager:
        class: Kapke\Bundle\MyPlaceBundle\DependencyInjection\ModuleManager
        arguments: [%kapke_my_place.modules%]
#    kapke_my_place.example:
#        class: %kapke_my_place.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
